<div id="graph_carreiras" style="width: 600px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">
<?php
	$categories = array();
	foreach( $this->carreiras_total as $key => $value )
	{
		$categories[] = ucfirst($key);
	}
?>
Highcharts.chart('graph_carreiras', {
  chart: {
    type: 'column'
  },
  title: {
    text: 'Aptidão por Carreiras'
  },
  xAxis: {
    categories: ["<?php echo implode('","', $categories); ?>"]
  },
  yAxis: {
    min: 0,
    max: 100,
    title: {
      text: ''
    }
  },
  series: [{
    name: 'Carreiras',
    data: [<?php echo implode(',', $this->carreiras_total); ?>]
  }]
});
</script>
			