<!doctype html>
<html lang="en">
<head>
	<base href="/" />
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>

<body class="<?php echo (isset($this->layout()->me->config['navClean']) && $this->layout()->me->config['navClean'] == 'true') ? 'nav-clean' : null; ?>">
<div id="main">
	
	<!-- SIDEBAR -->
	<?php echo $this->partial('layout/partials/sidebar'); ?>

	<div id="content">
		
		<header>
			<div class="row">
			
				<div class="column column-10 ajst-line">
					<span class="user-img" style="background: url('/assets/application/img/cartao/<?php echo $this->layout()->me->imagem;?>');margin-left: 50px; display: inline-block;background-position: center; background-size: cover;width: 60px; height: 63px;"></span>
					<span class="user-name"><?php echo $this->layout()->me->nome;?></span>
				</div>
				<div class="column column-2">
					
					<ul class="menu inline" >
						<?php if( !empty($this->layout()->me->administrador) ): ?>
						<li>
							<a href="./painel/login/voltar-para-minha-conta" class="featured">
								<i class="fa fa-arrow-left"></i> MINHA CONTA
							</a>
						</li>
						<?php endif; ?>
						
						<li>
							<a href="./painel/login/sair" class="featured font-medium" title="Sair">
								<i style="color: #a4a4a4;" class="fa fa-power-off"></i>
							</a>
						</li>
						
						<li style="background-color: #13939e; width: 60px; height: 60px; text-align: center;">
							<a href="/" class="font-medium" title="Ir para o site" target="_blank">
								<i class="fa fa-external-link"></i>
							</a>
						</li>
					</ul>
					
				</div>
				
			</div>
		</header>
		
		<section>
			<?php echo $this->message(); ?>
			<?php echo $this->content; ?>
		</section>
		
	</div>
	
	<footer>
		<span class="copyright">Copyright &copy; <b>Wantu</b> 2018. Todos os direitos reservados.</span>
		<span class="author">Powered by <a href="http://www.naiche.com.br" target="_blank">Naiche</a>.</span>
	</footer>
	
</div>
</body>
</html>