<?php 
$title = '<span style="margin-top:-9px; display: inline-block;">Trilha 6</span>';
	include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="topo-pontos">
	<div class="container">
		<h1>Quais são suas principais competências?</h1>
		<p>
			As competências são formadas pelos conhecimentos, habilidades e atitudes dos indivíduos. Agora você irá fará uma auto-avaliação do seu nível de proficiência em diversas competências. Leia o significado da competência e seja sincero ao se avaliar, afinal, reconhecer que tem algo a melhorar é o primeiro passo para seu desenvolvimento. Bora?!
		</p>
		
		<div class="line"></div>
	</div>
</div>

<div id="test-content">
	<div class="container">
		<form method="post" style="float: left;" id="form-submit">
			
			<div class="box-question">
			
				<div class="question-text">
					<span>1. Autodesenvolvimento e gestão do conhecimento</span>
					<p>
						Capacidade de aceitar as próprias necessidades de desenvolvimento e de investir tempo e energia no aprendizado contínuo.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p1">1</a>
					<a data-value="2" data-name="p1">2</a>
					<a data-value="3" data-name="p1">3</a>
					<a data-value="4" data-name="p1">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>
			
			<div class="box-question">
			
				<div class="question-text">
					<span>2. Capacidade de adaptação e flexibilidade</span>
					<p>
						Capacidade para adaptar-se oportunamente às diferentes exigências do meio, sendo capaz de rever sua postura diante de novas realidades. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p2">1</a>
					<a data-value="2" data-name="p2">2</a>
					<a data-value="3" data-name="p2">3</a>
					<a data-value="4" data-name="p2">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>3. Capacidade empreendedora</span>
					<p>
						Facilidade para identificar novas oportunidades de ação e capacidade para propor e implementar soluções aos problemas e necessidades que se apresentam de forma assertiva e adequada ao contexto. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p3">1</a>
					<a data-value="2" data-name="p3">2</a>
					<a data-value="3" data-name="p3">3</a>
					<a data-value="4" data-name="p3">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>4. Capacidade negocial</span>
					<p>
						 Capacidade de se expressar e de ouvir o outro, buscando o equilíbrio de soluções satisfatórias nas propostas apresentas pelas partes.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p4">1</a>
					<a data-value="2" data-name="p4">2</a>
					<a data-value="3" data-name="p4">3</a>
					<a data-value="4" data-name="p4">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>5. Comunicação e interação</span>
					<p>
						 Capacidade para agir com as pessoas apresentando facilidade para ouvir, processar e compreender a mensagem. Facilidade para transmitir e argumentar com coerência e clareza, promovendo feedback sempre que necessário. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p5">1</a>
					<a data-value="2" data-name="p5">2</a>
					<a data-value="3" data-name="p5">3</a>
					<a data-value="4" data-name="p5">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>6. Criatividade e inovação</span>
					<p>
						 Capacidade para conceber e adotar soluções inovadoras, viáveis e adequadas para as situações apresentadas.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p6">1</a>
					<a data-value="2" data-name="p6">2</a>
					<a data-value="3" data-name="p6">3</a>
					<a data-value="4" data-name="p6">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>7. Cultura da qualidade</span>
					<p>
						 Postura orientada para a busca contínua da satisfação das necessidades e superação das expectativas dos clientes internos e externos.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p7">1</a>
					<a data-value="2" data-name="p7">2</a>
					<a data-value="3" data-name="p7">3</a>
					<a data-value="4" data-name="p7">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>8. Liderança</span>
					<p>
						 Capacidade para catalisar os esforços grupais de forma a atingir ou superar os objetivos organizacionais, estabelecendo um clima motivador, formando parcerias e estimulando o desenvolvimento da equipe. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p8">1</a>
					<a data-value="2" data-name="p8">2</a>
					<a data-value="3" data-name="p8">3</a>
					<a data-value="4" data-name="p8">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>9. Motivação e energia para o trabalho</span>
					<p>
						 Capacidade para demonstrar interesse e energia pelas atividades que executa, tomando iniciativas e mantendo atitude de disponibilidade.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p9">1</a>
					<a data-value="2" data-name="p9">2</a>
					<a data-value="3" data-name="p9">3</a>
					<a data-value="4" data-name="p9">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>10. Orientação para resultados</span>
					<p>
						 Capacidade de trabalhar sob a orientação de objetivos e metas, focando os resultados a alcançar.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p10">1</a>
					<a data-value="2" data-name="p10">2</a>
					<a data-value="3" data-name="p10">3</a>
					<a data-value="4" data-name="p10">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>11. Planejamento e organização</span>
					<p>
						 Capacidade para planejar e organizar as ações para o trabalho, atingindo resultados por meio do estabelecimento de prioridades, metas tangíveis, mensuráveis e dentro de critérios de desempenho válidos. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p11">1</a>
					<a data-value="2" data-name="p11">2</a>
					<a data-value="3" data-name="p11">3</a>
					<a data-value="4" data-name="p11">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>12. Relacionamento interpessoal</span>
					<p>
						Habilidade para interagir de forma empática, inclusive diante de situações conflitantes, demonstrando atitudes assertivas, comportamentos maduros e não combativos.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p12">1</a>
					<a data-value="2" data-name="p12">2</a>
					<a data-value="3" data-name="p12">3</a>
					<a data-value="4" data-name="p12">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>13. Tomada de decisão</span>
					<p>
						 Capacidade de buscar e selecionar alternativas, identificando a que garanta o melhor resultado, cumprindo prazos definidos e considerando limites e riscos. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p13">1</a>
					<a data-value="2" data-name="p13">2</a>
					<a data-value="3" data-name="p13">3</a>
					<a data-value="4" data-name="p13">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>14. Trabalho em equipe</span>
					<p>
						 Capacidade para desenvolver ações compartilhadas, catalisando esforços e obtendo resultados por meio da cooperação mútua. 
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p14">1</a>
					<a data-value="2" data-name="p14">2</a>
					<a data-value="3" data-name="p14">3</a>
					<a data-value="4" data-name="p14">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
				<div class="line-full-ft"><div class="line-ft"></div></div>
			</div>

			<div class="box-question">
			
				<div class="question-text">
					<span>15. Visão sistêmica</span>
					<p>
						 Capacidade para perceber a interação e a interdependência das partes que compõem o todo, visualizando tendências e possíveis ações capazes de influenciar o futuro.
					</p>
				</div>
				<div class="box-respostas">
					<span>Auto-Avaliação</span>
					<a data-value="1" data-name="p15">1</a>
					<a data-value="2" data-name="p15">2</a>
					<a data-value="3" data-name="p15">3</a>
					<a data-value="4" data-name="p15">4</a>
					<p>1 | Não Atende  •  2  | Em Desenvolvimento  •  3  | Atende  •  4  | Supera</p>
				</div>
				
			</div>
			
			
			<div class="button-line">
				<a href="javascript:$('#form-submit').submit();">CONCLUIR</a>
			</div>


			<input type="hidden" name="method" value="salvar" />
		</form>
	</div>
</div>

<script>

    var offset = $("#draggable").offset();

	//funcao de focar o meio

    $('html, body').animate({scrollTop: 1}, 0);
    $('html, body').animate({scrollTop: 0}, 0);
	
    $(window).scroll(function() {

		var alturaTela = $('body').height();
		var AlturaTelaMetade = alturaTela / 1.5;
		var scrollTop = $(window).scrollTop() + AlturaTelaMetade;

		$('.box-question').removeClass('active');
		
		$('.box-question').each(function(){

			var alturaQuestion = $(this).offset().top;
			var heightQuestion = $(this).height();
			var alturaQuestionElement = alturaQuestion + heightQuestion + 70;
			
			if ( scrollTop >= alturaQuestion && scrollTop <= alturaQuestionElement ) {

				$(this).addClass('active');
				$(this).attr('data-offset-top', alturaQuestion);

			}
			
	    });
        
    });

	$(document).on('click', '.box-respostas > a', function() {

		var alturaQuestion = $(this).parents('.box-question').offset().top - $(this).parents('.box-question').height() - 240;
		var alturaTela = $(window).scrollTop();
		
		$(this).addClass('active').siblings().removeClass('active');

		//verificar se esta active, pra rodar a altura da div pra baixo + scrollTop do scroll.

		if ( $(this).parents('.box-question').hasClass('active') ) {

			var nextQuestion = $(window).scrollTop() + $(this).parents('.box-question').height() + 70;
			
			$('html, body').animate({
				scrollTop: nextQuestion
			}, 1000);

		} else {

			$('html, body').animate({
				scrollTop: alturaQuestion
			}, 1000);

		}
		
		var value = $(this).attr('data-value');
		var name = $(this).attr('data-name');

		$(this).parent().find('input').remove();
		
		$(this).parent().append('<input type="hidden" name="'+name+'" value="'+value+'"/>');

		

	});
</script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
	function submitForm(){

		$('.box-drop').submit();

	}
</script>