<?php
$title = '<span style="margin-top:-9px; display: inline-block;">Trilha 6</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="content-sucesso">
	<div class="container">
		<p class="tittle-box">
			Você concluiu uma etapa importante da Trilha Wantu. Corra e acesse o seu Relatório Match, que indica qual carreira combina mais com você!
		</p>
		<p class="text">
			Baixe agora seu relatório
		</p>
		<a class="perfil" href="/minha-conta" style="float: none;">Voltar para o painel</a>
	</div>
</div>