<meta name="format-detection" content="telephone=no">

<div class="bgfull">

	<div class="cartao">
		
		<a class="wantul"></a>
		<img class="f-perfil" alt="" src="/assets/application/img/cartao/raquel.png">
		
		<div class="dados">
			<p class="nome">Raquel Santos Soares Menezes</p>
			<p class="cargo">Pessoas e carreiras</p>
			<p class="telefone" style="margin-left: -3px"><img class="img-ico" alt="" src="/assets/application/img/cartao/phone-call.png">
				<a class="telefone" target="_blank" href="<?php echo \Naicheframework\Helper\Convert::whatsapp('5534991671144', ''); ?>">(34) 9 9167 1144</a>
			</p>
			<p class="site"><i class="fab fa-linkedin-in" style="margin-right: 27px; color: #9c23a3;"></i><a href="https://www.linkedin.com/in/raquel-santos-soares-menezes-b907666/" target="_blank">LinkedIn</a></p>
			<p class="email"><img class="img-ico" alt="" src="/assets/application/img/cartao/envelope.png">raquel@wantu.com.br</p>
			<p class="site"><img class="img-ico" alt="" src="/assets/application/img/cartao/link.png"><a href="http://buscatextual.cnpq.br/buscatextual/visualizacv.do?metodo=apresentar&id=K4772948H3" target="_blank">bit.ly/lattesraquels</a></p>
		</div>
		<div class="infos">
			<p class="conheca">Conheça a <img alt="" src="/assets/application/img/cartao/wantu-logow.png"></p>
			<p class="info-mini">Clique nos ícones abaixo:</p>
			<ul class="redes">
				<li><a href="https://wantu.com.br"><img style="margin-top: 12px;" alt="" src="/assets/application/img/cartao/u-mini.png"></a></li>
				<li><a href="https://www.youtube.com/channel/UCBXqZioDHxhh9Ek9GNsKU0w"><i style="margin-left: 6px;" class="fas fa-play"></i></a></li>
				<li><a href="https://www.instagram.com/wantucarreiras/"><i class="fab fa-instagram"></i></a></li>
			</ul>
			<a class="site" href="https://wantu.com.br">www.wantu.com.br</a>
		</div>
	</div>

</div>