<?php 
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 3</span>';
	include 'module/Application/view/partials/headers/topo-teste.phtml';
?>
<link href="/assets/application/js/rangeslider/nouislider.min.css" media="" rel="stylesheet" type="text/css">
<div class="container" id="anc-aqui">
	
	<form class="pesq-3" method="post" id="form-submit">
		
		<p class="pesq-tittle">
			17. Veja as imagens e escolha aquela que represente<br>
			o papel que você deseja exercer na sua carreira: 
		</p>
		<p class="pesq-desc">
			Escolha uma das imagens abaixo
		</p>
		
		<div class="options" data-question="<?php echo $_GET['pg']; ?>">
		
			<a class="option" data-name="Gerencial" data-value="5" style="background: url('/assets/application/img/pesquisa3/option-5.png'); width:580px; height: 306px; margin-right: 45px;"></a>
			<a class="option" data-name="Especialista" data-value="5" style="background: url('/assets/application/img/pesquisa3/option-6.png') ;width:580px; height: 306px; margin-right: 45px;"></a>
			
		</div>
		
		<input type="hidden" name="prev" value="<?php echo $prev; ?>">
		<input type="hidden" name="next" value="<?php echo $next; ?>">	
		<input type="hidden" name="p<?php echo $_GET['pg']; ?>" class="result">
	
	</form>
	
	<div class="line-buttons">
		
		<a class="button width-ajst" href="trilha3?pg=<?php echo $prev; ?>">Voltar</a>
		
		<div class="pagination">
			
			<a class="arrow-prev" href="aptidoes-profissionais?pg=<?php echo $prev; ?>"><i class="fas fa-caret-left"></i></a>
			<p><?php echo $_GET['pg'];?> | 24 </p>
			<a class="arrow-next" href="javascript:$('#form-submit').submit();"><i class="fas fa-caret-right"></i></a>
		
		</div>
	
		<a class="button-blue width-ajst" href="javascript:$('#form-submit').submit();">Próxima</a>
	
	</div>
	
</div>
