<?php 
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 3</span>';
	include 'module/Application/view/partials/headers/topo-teste.phtml';
?>
<link href="/assets/application/js/rangeslider/nouislider.min.css" media="" rel="stylesheet" type="text/css">
<div class="container" id="anc-aqui">
	
	<form class="pesq-3" method="post" id="form-submit">
		
		<p class="pesq-tittle">
			22. Leia os 2 anúncios de emprego e escolha<br>
			qual você teria mais intenção de se candidatar: 
		</p>
		<p class="pesq-desc">
		Escolha uma das imagens abaixo
		</p>
		
		<div class="options" data-question="<?php echo $_GET['pg']; ?>">
		
			<a class="option" data-name="Internacional" data-value="5" style="background: url('/assets/application/img/pesquisa3/option-9.png'); width:501px; height: 394px;"></a>
			<a class="option" data-name="" data-value="0" style="background: url('/assets/application/img/pesquisa3/option-10.png') ;width:501px; height: 394px;"></a>
			
		</div>
		
		<input type="hidden" name="prev" value="<?php echo $prev; ?>">
		<input type="hidden" name="next" value="<?php echo $next; ?>">		
		<input type="hidden" name="p<?php echo $_GET['pg']; ?>" class="result" value="3">
	
	</form>
	
	<div class="line-buttons">
		
		<a class="button width-ajst" href="trilha3?pg=<?php echo $prev; ?>">Voltar</a>
		
		<div class="pagination">
			
			<a class="arrow-prev" href="aptidoes-profissionais?pg=<?php echo $prev; ?>"><i class="fas fa-caret-left"></i></a>
			<p><?php echo $_GET['pg'];?> | 24 </p>
			<a class="arrow-next" href="javascript:$('#form-submit').submit();"><i class="fas fa-caret-right"></i></a>
		
		</div>
	
		<a class="button-blue width-ajst" href="javascript:$('#form-submit').submit();">Próxima</a>
	
	</div>
	
</div>
