<div id="banner">
	<div class="banner">
		<div class="container">
		
			<div class="conteudo">
				<p>
					Tecnologia exclusiva<br>
					de <span>People Analytics</span>
				</p>
			</div>
		
		</div>
	</div>
</div>

			<div class="breadcrumb" style="margin-top: 20px;">
				<div class="container">
					<ul>
						<?php foreach ($this->layout()->breadcrumb as $key => $row):?>
							<li><a href="<?php echo $row ?>"><?php echo $key ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>

<div id="content">
	<div class="container">
		
		<div class="sobre-text">
			
			<div class="sobre-text-1">
				<div class="sobre-left">
					<p class="tittle">Wantu?</p>
					<p class="text">
						Uma plataforma interativa de desenvolvimento de carreira de jovens. Nosso propósito é despertar e potencializar os seus talentos, tornando-os protagonistas de suas carreiras.
						<br><br>
						A WantU surgiu a partir da identificação de uma “dor aguda” entre jovens de não se conhecerem o suficiente para responder à velha pergunta: “o que eu quero da vida?”. Reunindo uma equipe de duas professoras universitárias acostumadas a ouvir as queixas de estudantes acerca dos grandes desafios de iniciar uma carreira, a WantU nasce com uma proposta totalmente inovadora para o planejamento de carreira do público jovem. O sonho de suas fundadoras sempre foi oferecer uma solução para facilitar a travessia da fronteira que parece separar a universidade do mercado de trabalho. Com base na experiência de suas sócias, chega ao mercado em 2018 pronta para transformar esse processo em um aprendizado consciente, planejado e racional, no qual o protagonista é o próprio jovem.
					</p>
				</div>
				<div class="sobre-right">
					
					<img alt="" src="/assets/application/img/sobre-nos/obj01.png">			
					
				</div>
			</div>
			
			<div class="sobre-text-2">
				<ul>
					<li>
						<img alt="" src="/assets/application/img/sobre-nos/image-founder-1.png">
						<p>Raquel Santos Soares Menezes</p>	
						<span>Founder</span>				
					</li>		
					<li>
						<img alt="" src="/assets/application/img/sobre-nos/image-founder-2.png">
						<p>Francielih Dorneles Silva</p>	
						<span>Co-founder</span>				
					</li>
					<li>
						<img alt="" src="/assets/application/img/sobre-nos/image-founder-3.png">
						<p>Naiche</p>	
						<span>Parceiro</span>				
					</li>		
				</ul>
			</div>
			
		</div>		
	
	</div>
</div>