<div id="graph1" style="width: 600px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">
<?php
	$gap = array();
	$categories = array();
	foreach( $this->carreiras['publica'] as $key => $value )
	{
		$gap[$key] = 100 - $value;
		$categories[] = \Application\Classes\Relatorio::getCompetenciaNome($key);
	}
?>
Highcharts.chart('graph1', {
  chart: {
    type: 'column'
  },
  title: {
    text: 'Carreira Pública'
  },
  xAxis: {
    categories: ["<?php echo implode('","', $categories); ?>"]
  },
  yAxis: {
    min: 0,
    title: {
      text: ''
    }
  },
  tooltip: {
    pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>',
    shared: true
  },
  plotOptions: {
    column: {
      stacking: 'percent'
    },
    pie: { 
        colors: ['#cc0707', '#2f5d24']
    }
  },
  series: [{
    name: 'GAP',
    color: '#cc0707',
    data: [<?php echo implode(',', $gap); ?>]
  },{
    name: 'Atual %',
    color: '#2f5d24',
    data: [<?php echo implode(',', $this->carreiras['publica']); ?>]
  }]
});
</script>
			