<?php \Naicheframework\Log\Log::error('404', array('url' => $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'])); ?>
<link href="./assets/css/error.css" media="screen" rel="stylesheet" type="text/css" />

<div id="bug">
	<div class="content">
		<div class="content-box">
			<p align="left" class="font-medium">ERRO</p>
			<p align="center" class="font-big">404</p>
			<p align="right" class="font-medium"><b>Ops!</b></p>
			<p align="right" class="font-normal">A página que você procurou não pode ser exibida</p>
		</div>
	</div>
</div>