<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 1</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml'; ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<link href="/assets/application/js/extensions/jquery.tooltipster/dist/css/tooltipster.bundle.min.css" media="" rel="stylesheet" type="text/css">	

<div id="full-teste">
	<div class="container">
		<div class="progresso">
			<?php include 'module/Application/view/application/trilha1/progresso.phtml'; ?>
		</div>
		
		<div class="formulario">
			<div class="form-align">
				<p class="tittle" style="position: relative;">Atividades Extracurriculares<i class="info tooltip" title="Cursos em geral, workshops, eventos, etc">?</i></p>
				<form id="form-submit4" action="" method="post">
				
					<label class="select-100 right">
						<span>Você possui cursos extracurriculares?</span>
						<select name="possui_cursos"  onchange="$(this).val() == 'Sim' ? $('#formContent').slideDown() : $('#formContent').slideUp(); ">
							<option>Sim</option>
							<option>Não</option>
						</select>
					</label>
					
					<div id="formContent">
    					
    					<label class="input-50">
    						<span>Tipo</span>
    						<select name="tipo_de_curso" id="tipo_de_curso">
    							<option value="Evento">Evento</option>
    							<option value="Workshop">Workshop</option>
    							<option value="Minicurso">Minicurso</option>
    							<option value="Curso">Curso</option>
    							<option value="Outro">Outro</option>
    						</select>
    					</label>
    					
    					<label class="input-50 right">
    						<span>Qual?</span>
    						<input type="text" name="nome_do_curso" >
    					</label>
    					
    					<label class="select-100" id="nivel" style="display:none;">
    						<span>Nível</span>
    					</label>
    					
    					<label class="input-50">
    						<span>Carga horária</span>
    						<input type="text" name="carga_horaria" >
    					</label>
    					
    					<label class="input-50 right">
    						<span>Ano de conclusão</span>
    						<input type="text" class="calendarMD" name="conclusao_curso" >
    					</label>
    					
    					<input type="hidden" name="code" value="<?php echo $data->id_analise_de_curriculo; ?>"/>
     					<input type="hidden" name="method" value="salvarEtapa4" />
     					
 					</div>
				</form>
				
				<div class="button-add">
				<a class="button right button-curso ajust-buttonadd" href="javascript:$('#form-submit4').submit();">Adicionar</a>
				</div>
				
				<table class="cursos" cellspacing="0">
					<tbody>
					<?php foreach ( $data as $row ): $row = (object)$row; ?>
						<tr class="caixas">
							<td><p class="nome-curso"><?php echo $row->tipo_de_curso; ?></p></td>
							<td><p class="nivel-curso"><?php echo $row->nome_do_curso; ?></p></td>
							<td><a href="javascript:;" class="delete" data-href="/trilha1/deletar-curso/<?php echo $row->id_analise_cursos ?>"><i class="far fa-trash-alt"></i> Excluir</a></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
				
				<div class="buttons2">
					<a class="button-voltar" href="trilha1/pos-graduacao">voltar</a>
					<a class="button right confirmar" href="javascript:;" data-href="trilha1/idiomas">Próximo</a>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	   $("#tipo_de_curso").change(function(){ 

		   if ( $(this).val() == 'Curso' ) {

			   $('#nivel').fadeIn(0).append('<select name="nivel_do_curso"><option>Avançado</option><option>Intermediário</option><option>Básico</option></select>');

		   } else {

			   $('#nivel').fadeOut(0)
			   $('#nivel select').remove();

		   }
		      
	   });
	});
</script>

<script>

	$('.delete').on('click', function(){

		var hrefDelete = $(this).data('href');

		if( confirm("Deseja realmente fazer isso?") ) {

			location.href=hrefDelete;
			
		}

	});

</script>


<script>

	$('.confirmar').on('click', function(){

		var hrefDelete = $(this).data('href');

		$.confirm({
		    title: 'Cuidado!',
		    content: 'Clique em adicionar para salvar seus dados antes de avançar.',
		    buttons: {
		        Próximo: function () {
		        	location.href=hrefDelete;
		        },
		        Cancelar: function () {
		        }
		    }
		});

	});

</script>


<script type="text/javascript">
$('.tooltip').tooltipster({
	   animation: 'fade',
	   delay: 200,
	   theme: 'Light',
	   arrow: false,
});
</script>