<?php 
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 1</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml'; ?>

<div id="full-teste">
	<div class="container">
    		<div class="box-align">
    			<p class="tittle" style="font-size: 35px;">Parabéns, você deu o primeiro passo!</p>
    			<p class="texto-f-2">Atualize seu plano e siga para a Trilha Wantu</p>
    			<a class="button-blue" style="display: inline-block; float: none; padding: 15px 32px; border-radius: 7px; margin-right: 33px;" href="/trilha1/curriculo">Visualizar Currículo</a>
    			<a class="button" style="display: inline-block; float: none;" href="/checkout/planos">Atualize seu plano</a>
			</div>
	</div>
</div>