<?php
$title = '<span style="margin-top:-8px; display: inline-block;">Trilha 5</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="content-sucesso">
	<div class="container">
		<p class="tittle-box">
			Obrigado! Recebemos sua resposta
		</p>
		<p class="text">
			Baixe agora seu relatório
		</p>
		<a class="perfil" href="/minha-conta" style="float: none;">Voltar para o painel</a>
	</div>
</div>