<link href="/assets/application/js/extensions/jquery.perfect.scrollbar/css/perfect-scrollbar.min.css" media="" rel="stylesheet" type="text/css">	

<?php 
	$title = '<span style="margin-top:20px; display: inline-block;">Trilha 2</span>';
	include 'module/Application/view/partials/headers/topo-teste.phtml'; 
?>

<div id="conteudo">
	<div class="container">
		<div class="cont-left">
			<p class="tittle-box">
				Como você tende a se comportar nas diversas situações do dia-a-dia?
			</p>
			<p class="text">
				<span>Olá! </span>Vamos agora ajudá-lo a identificar seu perfil comportamental. Para isso, basta que selecione entre as palavras abaixo aquelas que mais representam como você realmente age. Não fique pensando muito...Leia e marque aquelas alternativas que fazem sentido de imediato. Marque quantas opções quiser.
			</p>
		</div>
		<div class="cont-right">
			<a class="img-right"></a>
		</div>
		<div class="cont-full">
			<p class="tittle-box">
				Quais são as suas características?
			</p>
			<p class="text">
				Arraste para o campo cinza todas as caracterícas que forem compatíveis com você
			</p>
		</div>
	</div>
</div>

<div id="content">
	<div class="container">
	
		<div class="box-options">
			<a class="option" data-value="1" data-name="Curioso">
				Curioso
			</a>
			<a class="option" data-value="2" data-name="Gosta de privacidade">
				Gosta de privacidade
			</a>
			<a class="option" data-value="2" data-name="Racional">
				Racional
			</a>
			<a class="option" data-value="3" data-name="Reservado">
				Reservado
			</a>
			<a class="option" data-value="2" data-name="Sabe se preservar">
				Sabe se preservar
			</a>
			<a class="option" data-value="3" data-name="Antecipa necessidades">
				Antecipa necessidades
			</a>
			<a class="option" data-value="4" data-name="Facilmente entediado">
				Facilmente entediado
			</a>
			<a class="option" data-value="1" data-name="Impulsivo">
				Impulsivo
			</a>
			<a class="option" data-value="2" data-name="Suave, tem tato">
				Suave, tem tato
			</a>
			<a class="option" data-value="3" data-name="Preocupa-se com os outros">
				Preocupa-se com os outros
			</a>
			<a class="option" data-value="4" data-name="Assertivo">
				Assertivo
			</a>
			<a class="option" data-value="4" data-name="Assume riscos">
				Assume riscos
			</a>
			<a class="option" data-value="1" data-name="Confiante">
				Confiante
			</a>
			<a class="option" data-value="4" data-name="Corajoso">
				Corajoso
			</a>
			<a class="option" data-value="4" data-name="Independente">
				Independente
			</a>
			<a class="option" data-value="3" data-name="Construtor de confiança">
				Construtor de confiança
			</a>
			<a class="option" data-value="3" data-name="Esquiva-se de conflito">
				Esquiva-se de conflito
			</a>
			<a class="option" data-value="3" data-name="Mediador">
				Mediador
			</a>
			<a class="option" data-value="1" data-name="Persuasivo">
				Persuasivo
			</a>
			<a class="option" data-value="3" data-name="Paciente">
				Paciente
			</a>
			<a class="option" data-value="1" data-name="Bom comunicador">
				Bom comunicador
			</a>
			<a class="option" data-value="1" data-name="Diz a coisa certa">
				Diz a coisa certa
			</a>
			<a class="option" data-value="1" data-name="Espontâneo">
				Espontâneo
			</a>
			<a class="option" data-value="1" data-name="Gosta de pessoas">
				Gosta de pessoas
			</a>
			<a class="option" data-value="1" data-name="Senso de Humor">
				Senso de Humor
			</a>
			<a class="option" data-value="4" data-name="Criador de Alternativas">
				Criador de Alternativas
			</a>
			<a class="option" data-value="4" data-name="Criativo">
				Criativo
			</a>
			<a class="option" data-value="1" data-name="Gosta de variedade">
				Gosta de variedade
			</a>
			<a class="option" data-value="1" data-name="Inovador">
				Inovador
			</a>
			<a class="option" data-value="4" data-name="Extrovertido">
				Extrovertido
			</a>
			<a class="option" data-value="2" data-name="Alto nível de exigência">
				Alto nível de exigência
			</a>
			<a class="option" data-value="2" data-name="Meticuloso">
				Meticuloso
			</a>
			<a class="option" data-value="2" data-name="Obedece as regras">
				Obedece as regras
			</a>
			<a class="option" data-value="2" data-name="Orientado para detalhes">
				Orientado para detalhes
			</a>
			<a class="option" data-value="2" data-name="Perfeccionista">
				Perfeccionista
			</a>
			<a class="option" data-value="4" data-name="Influenciador">
				Influenciador
			</a>
			<a class="option" data-value="3" data-name="Líder">
				Líder 
			</a>
			<a class="option" data-value="3" data-name="Mentor">
				Mentor
			</a>
			<a class="option" data-value="3" data-name="Positivo">
				Positivo
			</a>
			<a class="option" data-value="4" data-name="Toma a dianteira">
				Toma a dianteira
			</a>
			<a class="option" data-value="1" data-name="Alma da festa">
				Alma da festa
			</a>
			<a class="option" data-value="1" data-name="Animado">
				Animado
			</a>
			<a class="option" data-value="4" data-name="Cheio de energia">
				Cheio de energia
			</a>
			<a class="option" data-value="1" data-name="Energético">
				Energético
			</a>
			<a class="option" data-value="4" data-name="Rápido">
				Rápido
			</a>
			<a class="option" data-value="4" data-name="Ambicioso">
				Ambicioso
			</a>
			<a class="option" data-value="4" data-name="Competititvo">
				Competititvo
			</a>
			<a class="option" data-value="4" data-name="Determinado">
				Determinado
			</a>
			<a class="option" data-value="3" data-name="Objetivo">
				Objetivo
			</a>
			<a class="option" data-value="4" data-name="Orientado para resultados">
				Orientado para resultados
			</a>
			<a class="option" data-value="4" data-name="Controlador">
				Controlador
			</a>
			<a class="option" data-value="3" data-name="Metódico">
				Metódico
			</a>
			<a class="option" data-value="2" data-name="Organizado">
				Organizado
			</a>
			<a class="option" data-value="2" data-name="Planeja com antecedência">
				Planeja com antecedência
			</a>
			<a class="option" data-value="2" data-name="Previsível">
				Previsível
			</a>
			<a class="option" data-value="3" data-name="Agradável">
				Agradável
			</a>
			<a class="option" data-value="3" data-name="Amigável">
				Amigável
			</a>
			<a class="option" data-value="1" data-name="Simpático">
				Simpático		
			</a>
			<a class="option" data-value="1" data-name="Sociável">
				Sociável
			</a>
			<a class="option" data-value="2" data-name="Leal">
				Leal
			</a>
			<a class="option" data-value="2" data-name="Considera as opções">
				Considera as opções
			</a>
			<a class="option" data-value="3" data-name="Bem informado">
				Bem informado
			</a>
			<a class="option" data-value="3" data-name="Cuidadoso">
				Cuidadoso
			</a>
			<a class="option" data-value="4" data-name="Decidido">
				Decidido
			</a>
			<a class="option" data-value="4" data-name="Forte opinião">
				Forte opinião
			</a>
			<a class="option" data-value="3" data-name="Empático">
				Empático
			</a>
			<a class="option" data-value="3" data-name="Compreensivo">
				Compreensivo
			</a>
			<a class="option" data-value="3" data-name="Cooperativo">
				Cooperativo
			</a>
			<a class="option" data-value="3" data-name="Fácil de lidar">
				Fácil de lidar
			</a>
			<a class="option" data-value="4" data-name="Comprometido">
				Comprometido
			</a>
			<a class="option" data-value="2" data-name="Cauteloso na ação">
				Cauteloso na ação
			</a>
			<a class="option" data-value="1" data-name="Não orientado para detalhes">
				Não orientado para detalhes
			</a>
			<a class="option" data-value="2" data-name="Ordeiro">
				Ordeiro
			</a>
			<a class="option" data-value="1" data-name="Percebe o quadro geral">
				Percebe o quadro geral
			</a>
			<a class="option" data-value="2" data-name="Sistemático">
				Sistemático
			</a>
		</div>
		
		<form class="box-drop" method="post" action="/trilha2/send">
			
			<input type="hidden" name="id_login" value="<?php echo $this->layout()->me->id_login; ?>">			
		</form> 
		
		<div class="line-buttons">
			<a href="javascript:submitForm();;" class="perfil">Enviar reposta</a>
		</div>
		
	</div>
</div>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>

	function submitForm(){

		$('.box-drop').submit();
		
	}

	$( function() {

		var i = 0;
		$('.box-options .option').each( function (){

			$(this).attr('data-id', i);
			i++;
			
		});

		$(document).on('click', '.box-options a.option', function(){

			var value = $(this).attr('data-value');
			var name = $(this).attr('data-name');
			var id = $(this).attr('data-id');
			var text = $(this).text();
			
			var htmlEnd  = '<a class="option" data-value="'+value+'" data-name="'+name+'" data-id="'+id+'">';
				htmlEnd += text;
				htmlEnd += '<i class="close">X</i>';
				htmlEnd += '<input type="hidden" name="option['+id+'][name]" value="'+name+'">';
				htmlEnd += '<input type="hidden" name="option['+id+'][value]" value="'+value+'">';
				htmlEnd += '<input type="hidden" name="option['+id+'][key]" value="'+id+'">';
				htmlEnd += '</a>';

			$(this).remove();
			
			$('.box-drop').append(htmlEnd);
			ReordenaOptionsBox();
			
			
		});
		
		$('.box-options, .box-drop').sortable({
			connectWith: '.box-drop',
			revert: true,
			placeholder: {
		        element: function(currentItem) {
		            return $('<a class="option placeholder">&nbsp;</a>')[0];
		        },
		        update: function(container, p) {
		            return;
		        }
		    }, stop: function( event, ui ) {
	
		    	ReordenaOptionsBox();
	
			}
	    
		}).disableSelection();

		$(document).on('click', '.close', function(){

			var attributes = $(this).parent().clone().prependTo('.box-options');
			$(this).parent().remove();
			$('.box-options .option i').remove();
			$('.box-options .option input').remove();

		});
		
	});

	function ReordenaOptionsBox(){

		$('.box-drop .option').each( function (){

			$(this).find('.close').remove();
			$(this).find('input').remove();

			var value = $(this).attr('data-value');
			var name = $(this).attr('data-name');
			var id = $(this).attr('data-id');

			$(this).append('<i class="close">X</i>');
			$(this).append('<input type="hidden" name="option['+id+'][name]" value="'+name+'"/>');
			$(this).append('<input type="hidden" name="option['+id+'][value]" value="'+value+'"/>');
			$(this).append('<input type="hidden" name="option['+id+'][key]" value="'+id+'"/>');

		});
	
	}
</script>
<style>
.ui-sortable-placeholder { display:none !important; }
</style>