<div id="banner">
	<div class="banner">
		<div class="container">
		
			<div class="conteudo">
				<p>
					Política de<br>
					<span>Privacidade</span>
				</p>
			</div>
		
		</div>
	</div>
</div>

			<div class="breadcrumb" style="margin-top: 20px;">
				<div class="container">
					<ul>
						<?php foreach ($this->layout()->breadcrumb as $key => $row):?>
							<li><a href="<?php echo $row ?>"><?php echo $key ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>

<div id="content">
	<div class="container">
		
		<div class="sobre-text">
			
			<div class="sobre-text-1">
				<p class="text">
					Esta declaração de <b>Política de Privacidade</b> explica as práticas da Wantu, incluindo as suas escolhas como usuário, referentes à coleta, utilização e divulgação de certas informações, incluindo suas informações pessoais. 
				</p>
			</div>
			
			<div class="sobre-text-2">
			
				<div class="faq boxGrp ">
				
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>1.</span>Contato com a wantu </p>
							<div class="faq-left">
								<p>
									Em caso de qualquer dúvida, é possível nos contatar através do e-mail <b>contato@wantu.com.br</b> ou mediante o telefone <b>(34) 99133 – 2301, no horário das 08h às 18h.</b>
									<br><br>De acordo com as regras de Política de Privacidade, a Wantu pode controlar as suas informações pessoais disponibilizadas no site. 
								</p>
							</div>
						</div>
					</div>

					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>2.</span>Coleta de dados </p>
							<div class="faq-left">
								<p>
									A Wantu armazena as informações no qual você disponibiliza no site no momento do cadastro, tais como: 
									<br><br><b>•</b> Nome completo, endereço de e-mail, endereço ou código postal, número de telefone, CPF, data de nascimento, CEP, Estado e Cidade. 
									<br><br><b>•</b> Informações coletadas automaticamente pela Wantu: A Wantu também coleta informações sobre qual o tipo de dispositivo você está acessando a plataforma, tais como: Dispositivos móveis, computadores e também IDs ou outros identificadores únicos de aparelhos;
									<br><br><b>•</b> Também é possível armazenar informações como a utilização do serviço de atendimento ao cliente, tais como, data, hora e motivo do contato;
									<br><br><b>•</b> Por questões de segurança, a plataforma Wantu também armazena características de aparelhos que podem indicar a sua localização geográfica aproximada, através de navegadores e dados padrão de logs de servidores da Internet; 
									
								</p>
							</div>
						</div>
					</div>
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>3.</span>Uso de informações</p>
							<div class="faq-left">
								<p>
									A Wantu utiliza essas informações para a segurança de armazenamento dos seus dados e comprovar veracidade das informações do seu cadastro no caso de fraudes. 
								</p>
							</div>
						</div>
					</div>
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>4.</span>Divulgação de informações </p>
							<div class="faq-left">
								<p>
									A Wantu só divulgará seus dados cadastrados a terceiros, conforme os casos descritos abaixo: 
									<br><br><b>• Empresa Wantu:</b> Os dados podem ser compartilhados com os colaboradores da empresa Wantu conforme necessário, bem como para o armazenamento de dados e atendimento ao cliente. 
									<br><br><b>•  Prestadores de Serviços:</b> A Wantu pode contratar empresas terceirizadas, ou prestadoras de serviços para fornecer auxílio e serviços destinados aos usuários da Wantu. Assim como serviços de marketing, comunicação, otimização e pagamentos. 
									<br><br><b>• Empresas usuárias da Plataforma:</b> Empregadores que queiram recrutar, selecionar ou mapear o perfil de seus funcionários usando a Plataforma Wantu.
									
								</p>
							</div>
						</div>
					</div>
					
										<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>5.</span>Acesso aos perfis </p>
							<div class="faq-left">
								<p>
									Para tornar mais simples o acesso ao seu perfil, será possível utilizar a opção “Lembrar senha” ao acessar o site, assim, facilitando o uso do seu login. Porém, essa função não é utilizada obrigatoriamente e seu uso pode ser interrompido independente do dispositivo que o site for acessado. 
								</p>
							</div>
						</div>
					</div>
					
										<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>6.</span>Suas informações e direitos  </p>
							<div class="faq-left">
								<p>
									É possível solicitar acesso a todas suas informações pessoais fornecidas em seu cadastro, bem como corrigi-las. Para isso, basta acessar a seção “Login” no nosso site, onde você pode acessar e atualizar uma série de informações sobre sua conta, inclusive suas informações de contato ou outros dados.
								</p>
							</div>
						</div>
					</div>
					
										<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>7.</span>Segurança </p>
							<div class="faq-left">
								<p>
									A Wantu emprega medidas administrativas, lógicas, gerenciais e físicas razoáveis para proteger suas informações pessoais contra perdas, roubos e acesso, uso e alterações não autorizados.
								</p>
							</div>
						</div>
					</div>
					
										<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>8.</span>Crianças</p>
							<div class="faq-left">
								<p>
									É recomendado que somente usuários com 18 anos ou mais, acessem os serviços da Wantu. 
								</p>
							</div>
						</div>
					</div>
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>9.</span>Alterações à presente declaração de privacidade </p>
							<div class="faq-left">
								<p>
									A Wantu obtém o direito de mudar periodicamente essa Declaração de Política de Privacidade para atender a mudanças na legislação, exigências regulatórias ou operacionais. Acontecendo isso, todos os usuários serão comunicados. 
								</p>
							</div>
						</div>
					</div>
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<div class="faq-left">
								<p>
									<b>Última atualização: 17/04/2019 </b>
								</p>
							</div>
						</div>
					</div>
					
				</div>
			
			</div>
			
		</div>		
	
	</div>
</div>