<div id="banner">
	<div class="banner">
		<div class="container">
		
			<div class="conteudo">
				<p>
					<?php echo $result->titulo ?>
				</p>
			</div>
		</div>
	</div>
</div>
<div id="conteudo-blog">
	<div class="container">
		<p class="cont-tittle tittle"><?php echo $result->titulo ?></p>
		
		<p class="cont-text"> 
			<?php echo $result->texto ?>
		</p>
		
		
		<div class="line-butttons">
			
<!-- 			<div class="buttons-right"> -->
<!-- 				<p class="color-text">tags no artigo: <a href="javascript:;">Lorem</a>, <a href="javascript:;">Lorem</a>, <a href="javascript:;">Lorem</a></p> -->
<!-- 			</div> -->
			
			<a href="/blog" class="buttons-left">IR PARA O BLOG</a>
			
		</div>
	</div>
</div>
