<form class="etapa etapa4 animated card" method="post" action="/checkout" style="display: none;">
	
	<div class="column column-6 " style="text-align: center; ">
		<i class="fa fa-check-circle" style="font-size: 150px; color:#28a745;"></i>
		<h2 style="font-size: 30px; font-weight: 300;">Contratação efetuada com sucesso</h2>
		<h3 style="font-size: 20px; font-weight: 300;">Você já pode acessar a ferramenta com o login e senha definidos na primeira etapa </h3>
		<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/painel">Clique aqui para acessar</a>
	</div>

</form>