<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>


<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>12- Quando tenho que fazer trabalho em grupo na facul:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Logico-matematico" data-value="5">
					<span class="image losango"></span>
					<span class="text-opt" style="margin-top: 71px;">
						Monto um cronograma <br>
						e Divido tarefas.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Intrapessoal" data-value="2">
					<span class="image estrela"></span>
					<span class="text-opt" style="margin-top: 70px;">
						Preferia fazer sozinho, <br>
						mas faço com o grupo.
					</span>
				</a>
				
				<a class="option"  data-name="Interpessoal" data-value="3">
					<span class="image coracao"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Adoro e já começo a <br>
						trocar ideias com a <br>
						equipe.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>