<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>18- Se eu pudesse fechar os olhos e transformar os melhores 	momentos da minha vida em uma obra de arte eu iria:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Musical" data-value="5">
					<span class="image triangulo"></span>
					<span class="text-opt" style="margin-top: 71px;">
						Compor uma música.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Espacial" data-value="2">
					<span class="image Quadrado"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Pintar um quadro da cena.
					</span>
				</a>
				
				<a class="option"  data-name="Naturalista" data-value="3">
					<span class="image Losango"></span>
					<span class="text-opt" style="margin-top: 47px;">
						Criar uma paisagem <br>
						natural.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>