<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>16- No horário do lanche na empresa, eu prefiro:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Interpessoal" data-value="5">
					<span class="image coracao"></span>
					<span class="text-opt" style="margin-top: 71px;">
						Ir para o café junto com <br>
						os colegas para colocar <br>
						o papo em dia.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Musical" data-value="2">
					<span class="image circulo"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Colocar meu fone e ouvir <br>
						minhas músicas <br>
						preferidas.
					</span>
				</a>
				
				<a class="option"  data-name="Intrapessoal" data-value="3">
					<span class="image estrela"></span>
					<span class="text-opt" style="margin-top: 47px;">
						Fazer meu lanche sozinho.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>