<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="topo-pesq">
	<div class="container">
		<div class="text-cont">
			<p class="tittle">Como você aprende melhor?</p>
			<p class="text">Procure responder às perguntas com honestidade e prossiga rapidamente.</p>
		</div>
		<div class="line"></div>
	</div>
</div>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			
			<div class="time-bar"></div>
			
			<div class="time-bar"></div>
			
			<div class="time-bar"><span class="p1">+10</span></div>
			
		</div>
		
		<div class="question">
			<p>1- Quando estou estudando para a prova eu:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Linguistica" data-value="5">
					<span class="image triangulo"></span>
					<span class="text-opt" style="margin-top: 71px;">
						Aprendo mais lendo os textos.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Musical" data-value="2">
					<span class="image circulo"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Aprendo mais quando ligo minha playlist preferida.
					</span>
				</a>
				
				<a class="option"  data-name="Espacial" data-value="3">
					<span class="image quadrado"></span>
					<span class="text-opt" style="margin-top: 47px;">
						Aprendo mais <br>
						transformando o texto <br>
						em esquemas e mapas <br>
						mentais com muitas <br>
						canetinhas coloridas.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>