<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>7- Resolvi me casar. Primeiro vou procurar:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Musical" data-value="5">
					<span class="image circulo"></span>
					<span class="text-opt" style="margin-top: 75px;">
						Uma banda top no <br>
						nosso estilo.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Espacial" data-value="2">
					<span class="image quadrado"></span>
					<span class="text-opt" style="margin-top: 82px;">
						Um espaço bem maneiro.
					</span>
				</a>
				
				<a class="option"  data-name="Logico-matematico" data-value="3">
					<span class="image losango"></span>
					<span class="text-opt" style="margin-top: 72px;">
						Uma planilha bem <br>
						estruturada para <br>
						controlar gastos.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>