<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>11- Meu chefe e colegas de trabalho sempre recorrem a mim porque eu:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Linguistica" data-value="5">
					<span class="image triangulo"></span>
					<span class="text-opt" style="margin-top: 71px;">
						Leio muito e sempre sou <br>
						bem informado.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Existencial" data-value="2">
					<span class="image grafico"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Porque me consideram <br>
						uma pessoa evoluída <br>
						espiritualmente.
					</span>
				</a>
				
				<a class="option"  data-name="Logico-matematico" data-value="3">
					<span class="image losango"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Faço cálculos e <br>
						análises financeiras <br>
						rapidamente.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>