<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>


<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>14- Meu programa favorito para domingo é:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Existencial" data-value="5">
					<span class="image grafico"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Ir a um lugar que possa <br>
						me aproximar de Deus <br>
						(igreja, por ex).
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Linguistica" data-value="2">
					<span class="image triangulo"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Ficar o dia todo lendo <br>
						um livro, vendo um filme <br>
						ou série.
					</span>
				</a>
				
				<a class="option"  data-name="Corporal" data-value="3">
					<span class="image positivo"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Fazer minha corrida/ <br>
						caminhada matinal.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>