<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>2- Quando estou a fim de alguém na balada:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Intrapessoal" data-value="5">
					<span class="image estrela"></span>
					<span class="text-opt" style="margin-top: 60px;">
						Fico na minha<br>
						observando e esperando<br>
						quem sabe a hora certa<br>
						de ir conversar.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Interpessoal" data-value="2">
					<span class="image coracao"></span>
					<span class="text-opt" style="margin-top: 65px;">
						Não penso 2 vezes e<br>
						logo vou puxar um <br>
						assunto.
					</span>
				</a>
				
				<a class="option"  data-name="Corporal" data-value="3">
					<span class="image positivo"></span>
					<span class="text-opt" style="margin-top: 76px;">
						Me aproximo, começo a<br>
						 dançar e enviar olhares 43.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>