<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>4- Quando preciso comprar um presente para alguém:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Linguistica" data-value="5">
					<span class="image triangulo"></span>
					<span class="text-opt" style="margin-top: 74px;">
						Dou um google com a <br>
						frase “dicas de presente”.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Intrapessoal" data-value="2">
					<span class="image estrela"></span>
					<span class="text-opt" style="margin-top: 68px;">
						Explico mais ou menos<br>
						o que penso e sigo as <br>
						sugestões da vendedora.
					</span>
				</a>
				
				<a class="option"  data-name="Interpessoal" data-value="3">
					<span class="image coracao"></span>
					<span class="text-opt" style="margin-top: 55px;">
						Compro sozinho com <br>
						facilidade, pois adoro <br>
						comprar presentes que <br>
						tenham a cara da pessoa.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>