<?php
$title = '<span style="margin-top:20px; display: inline-block;">Trilha 4</span>';
include 'module/Application/view/partials/headers/topo-teste.phtml';
?>

<div id="pesquisa">
	<div class="container">
	
		<div class="time">
			<span>00:45</span>
			<div class="time-bar"></div>
			<div class="time-bar"></div>
			<div class="time-bar"><span class="p1">+10</span></div>
		</div>
		
		<div class="question">
			<p>5- Um programa cultural que adoro fazer é:</p>
		</div>
		<form class="pesq" id="form-submit" method="post">
			<div class="options" data-question="<?php echo $_GET['pg']; ?>">
						
				<a class="option" data-name="Interpessoal" data-value="5">
					<span class="image coracao"></span>
					<span class="text-opt" style="margin-top: 68px;">
						Reunir com meus amigos<br>
						para uma nova<br> 
						experiência gastronômica.
					</span>
				</a>
				
				<a class="option" style="margin: 0 20px;"  data-name="Corporal" data-value="2">
					<span class="image positivo"></span>
					<span class="text-opt" style="margin-top: 66px;">
						Sair andando ao ar livre e <br>
						aproveitar para passar por <br>
						alguns lugares.
					</span>
				</a>
				
				<a class="option"  data-name="Espacial" data-value="3">
					<span class="image quadrado"></span>
					<span class="text-opt" style="margin-top: 66px;">
						Conhecer novos lugares, <br>
						apreciar paisagens e <br>
						obras de arte.
					</span>
				</a>
				
				<input type="hidden" name="prev" value="<?php echo $prev; ?>">
				<input type="hidden" name="next" value="<?php echo $next; ?>">
				<input type="hidden" class="result">
				
			</div>
		</form>	
	</div>
</div>