<div id="banner">
	<div class="banner">
		<div class="container">
		
			<div class="conteudo">
				<p>
					Plataforma<br>
					<span>100% online</span>
				</p>
			</div>
		
		</div>
	</div>
</div>

			<div class="breadcrumb" style="margin-top: 20px;">
				<div class="container">
					<ul>
						<?php foreach ($this->layout()->breadcrumb as $key => $row):?>
							<li><a href="<?php echo $row ?>"><?php echo $key ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>

<div id="content">
	<div class="container">
		
		<div class="sobre-text">
			
			<div class="sobre-text-1">
				<p class="tittle">Wantu?</p>
				<p class="text">
					A Want oferece um programa 100% online e interativo que auxilia o estudante a planejar sua carreira e alcançar o seu sucesso profissional. Nosso método exclusivo, baseado numa tecnologia própria de people analytics, te ajuda a descobrir quem você é, o que mais combina com seu perfil e como se desenvolver.  
				</p>
			</div>
			
			<div class="sobre-text-2">
			
				<div class="faq boxGrp  <?php echo ($i > 1) ? 'boxAccordionHide' : null; ?>">
				
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>1.</span>Como posso começar?</p>
							<i class="fa fa-angle-down"></i>
						</div>
						<div class="boxAccordionContent" style="display: none; float: left;">
							<div class="faq-left">
								<p>Faça seu cadastro e comece a criar seu perfil. Conforme você avança nas etapas sugeridas, seu perfil vai sendo atualizado. Além disso, você poderá baixar o seu Curriculum WantU, com base nas informações fornecidas. </p>
							</div>
							<div class="faq-right">
								<span class="image1"></span>
							</div>
						</div>
					</div>
					<hr>
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>2.</span>Onde estou?</p>
							<i class="fa fa-angle-down"></i>
						</div>
						<div class="boxAccordionContent" style="display: none; float: left;">
							<div class="faq-left">
								<p>
									É hora de focar no seu autoconhecimento! Com base nos seus diversos resultados, nosso algoritmo traça seu perfil profissional e indica a carreira que mais combina com você...já pensou em empreender? Ou ser um gerente de multinacional? Quem sabe servir ao país? Vamos te mostrar onde seu talento fala mais alto. 
								</p>
							</div>
							<div class="faq-right">
								<span class="image2"></span>
							</div>
						</div>
					</div>
					<hr>
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>3.</span>Onde quero chegar?</p>
							<i class="fa fa-angle-down"></i>
						</div>
						<div class="boxAccordionContent" style="display: none; float: left;">
							<div class="faq-left">
								<p>
									É hora de dar um start no seu planejamento de carreira! Levando em consideração suas aspirações e o que mais combina com seu perfil, vamos te ajudar a ter foco e metas claras para seu presente e futuro.  
								</p>
							</div>
							<div class="faq-right">
								<span class="image3"></span>
							</div>
						</div>
					</div>
					<hr>	
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq"><span>4.</span>O que vou fazer para chegar até lá? </p>
							<i class="fa fa-angle-down"></i>
						</div>
						<div class="boxAccordionContent" style="display: none; float: left;">
							<div class="faq-left">
								<p>
									É hora de aprender jogando! Vamos dar play numa jornada de desenvolvimento das competências mais importantes para a carreira almejada. De forma divertida, você vai potencializar seu talento, se preparar para enfrentar processos seletivos e vários outros desafios para realizar seus sonhos. 	
								</p>
							</div>
							<div class="faq-right">
								<span class="image4"></span>
							</div>
						</div>
					</div>
					<hr>
					
					<div class="faq-item">
						<div class="faq-top boxAccordionBt">
							<p class="tittle-faq ajst-font-m"><span>5.</span>Posso receber ofertas únicas de estágio e emprego?</p>
							<i class="fa fa-angle-down"></i>
						</div>
						<div class="boxAccordionContent" style="display: none; float: left;">
							<div class="faq-left">
								<p>
									Localizamos as melhores oportunidades de vagas disponíveis, e juntamos tudo num só lugar para facilitar o seu acesso às oportunidades de mercado que combinam com seu perfil. Candidate-se e dê logo o match que você sempre quis! 
								</p>
							</div>
							<div class="faq-right">
								<span class="image5"></span>
							</div>
						</div>
					</div>
					<hr>
				
				</div>
			
			</div>
			
		</div>		
	
	</div>
</div>